### ISSUE TITLE
Coincidence

### ISSUE THREAD

**Issue by gilesknap** [docent-net/mc-server-manager#1]
Hey, 

not really an issue, but I just discovered that you and I are developing practically the same thing simultaneously. I noticed because of our dependency on https://pypi.org/project/pystemd/. I just started yesterday and it looks like your project is a couple of days old too.

Mine is still rudimentary but fully working for start/stop/restart/enable/disable/console.

Maybe we should pool ideas. Feel free to use anything useful from https://github.com/gilesknap/minecraft-control

Cheers,
giles

**Comment by docent-net** [comment]
Hi GIles, thanks for this message :)

Yeah, looks like we're moving around the same area! However, I think I'm solving a different problem (but correct me as I'm probalby wrong :) ). 

My kid regularly plays MC with his friends as well as I teach him Python basics in MC world (using Spigot and Python API plugin). And I built them a server (a physical one). It's an old machine residing in the basement. It's enough for just one server instance. And the problem is that every time kids wanna play, or wanna have a new server or switch to a previous one - they depend on my manual work.

So the high - level goal is providing kids with UI, where they would be able to start chosen server instance, or create a brand new server. So I went through couple of projects that solve similar problems but none of those projects fit my case.

My setup for that server is a Fedora 31 host, where I have a systemd-container ([nspawn](https://www.freedesktop.org/software/systemd/man/systemd-nspawn.html)) for MC server (image built w/[mkosi](https://github.com/systemd/mkosi) and customized w/Ansible). 

And the idea is that MC server environment is kept on **/home/minecraft/minecraft-server** directory, while all server instances' data is under **/home/minecraft/servers-data** as subdirectories.

So, for now, I'm working on a CLI script that basically manages to switch between those server instances' (by proper symlinks).

And when this script is ready, I was thinking about some UI (maybe a one which could be also used from mobile device).

From security perspective, a systemd unit service (minecraft-server) is run from **minecraft** user so no need for elevated permissions. Same for UI - MC server doesn't use privileged TCP/UDP ports, so no need to sudo here.

So this is a bit of high and low - level perspectives. If you feel like this might be something we could join our forces - I'm all into it :) Surely we can also pool ideas and simply motivate and help each other.

**Comment by gilesknap** [comment]
Your requirements are similar to mine. I have been using a Raspberry Pi 4 as a Minecraft server and it hosts several of my sons friends reasonably well. But it cannot have more than one server running so this is to switch servers and switch worlds within a server.

The difference is that you are using containers. I guess that is more secure. Also I'm using systemd dbus and therefore require elevated privileges to make the switches. 

The project is a convenience for me rather than something I something for the kids to use. So I wont be handing out sudo rights! 

Your approach seems appealing if it is safe to hand over to the kids.

**Comment by docent-net** [comment]
About containers - it actually doesn't matter. The scripting and UI will be completely unaware of running inside of a container, on directly on a bare metal :)

As for those permissions - for now, I'm using [user services](https://www.brendanlong.com/systemd-user-services-are-amazing.html) but you have a very good point here - whether an unprivileged user may manage service via dbus. I believe so - but only when this is his own user service. I'm gonna test it, however.

And yes - the final goal is to handover this to kids so they can make use of it :)

**Comment by gilesknap** [comment]
Ah, maybe I don't need elevation then. I've been testing from my own account and assumed that service management was privileged but it makes sense if an account is allowed to manage its own services.

**Comment by gilesknap** [comment]
Thanks for the tip on using user services. I'm failing to get this to work with my service account, although it does work with my main account.

Have you managed to make this work?
```
giles@gknuc:~/minecraft-control$ systemctl --user enable minecraft2@DadNoahSurvival
Created symlink /home/giles/.config/systemd/user/multi-user.target.wants/minecraft2@DadNoahSurvival.service → /home/giles/.config/systemd/user/minecraft2@.service.

giles@gknuc:~/minecraft-control$ groups
giles adm cdrom sudo dip plugdev lpadmin lxd sambashare

giles@gknuc:~/minecraft-control$ su minecraft
Password: 

minecraft@gknuc:/home/giles/minecraft-control$ systemctl --user enable minecraft2@DadNoahSurvival
Failed to connect to bus: Permission denied

minecraft@gknuc:/home/giles/minecraft-control$ ls -l ~/.config/systemd/user/
total 4
-rw-r--r-- 1 minecraft minecraft 2146 Apr 18 17:30 minecraft2@.service
minecraft@gknuc:/home/giles/minecraft-control$ goups

minecraft@gknuc:/home/giles/minecraft-control$ groups
minecraft
```

**Comment by docent-net** [comment]
Yeah, works flawlessly. You're sudoing, so probably hitting this problem: https://serverfault.com/questions/936985/cannot-use-systemctl-user-due-to-failed-to-get-d-bus-connection-permission

I'd shoot, that if you create, enable and start this service as **giles** user (without sudoing into another user) it would work properly.

**Comment by gilesknap** [comment]
Thanks, this helped. But in fact the issue was that I was trying to re-use my system account 'minecraft' to run a user service. I created a new interactive account and then all was well.

The only remaining issue I encountered was when setting the account to 'linger'.

I got 
```
giles@gknuc:~/minecraft-control$ sudo loginctl enable-linger minecrafti
Could not enable linger: Read-only file system
```
But the workaround is apparently
```
sudo touch /var/lib/systemd/linger/minecrafti
```

**Comment by gilesknap** [comment]
Thanks for your help. I now have a fully working user service.

I took some hints from your code and also the recent answer to your query at https://github.com/facebookincubator/pystemd/issues/52

**Comment by gilesknap** [comment]
I'm now wondering if a user service is the correct way to go.

My original system service used this unit definition https://github.com/agowa338/MinecraftSystemdUnit/blob/master/minecraft%40.service which is tightly locked down.

A user account presents more of an attack surface for an internet facing service.

I've read of others using a system service and then controlling it from a normal user account with very restricted sudo rights to just manage the one service.

You have gone to some trouble to get a user service running so I wondered what your view was on this?

(also, I have so far failed to get my user service to start on reboot - this feature was easy with a system service)

**Comment by docent-net** [comment]
About starting on reboot - it was something about lingering afair:

- https://serverfault.com/questions/846441/loginctl-enable-linger-disable-linger-but-reading-linger-status
- https://www.brendanlong.com/systemd-user-services-are-amazing.html

Above should just work (however this may differ depending on Linux distro; some Linux distros integrated systems in very strange ways ending up with unexpected behaviours).

About user service and security. My kid plays MC with his friends, so they all connect to our server remotely making this server an internet-facing service (NATted, behind a firewall, but still :) ). And this is a java app like any other. I simply wanna lower the attack surface (least privileges rule). But of course, this may wary. So anything works for you better - I don't see anything wrong with running a normal system service as far as you're fully aware etc.

Btw - linked service unit is basically a [unit template](https://www.freedesktop.org/software/systemd/man/systemd.service.html). But it shouldn't really matter as template units also works fine with user services.

**Comment by gilesknap** [comment]
I'm on Ubuntu 19.10. My account does report that it is lingering. There are no issues with the service running when the user is logged out. Only at reboot time. I'll investigate further.

I have a double NAT (because Google WiFi) and firewall. So maybe a user service is safe enough really. Also, I don't think the sudo idea is great because I would have to abandon the psystemd library and instead launch systemctl in a subprocess.

The template unit is useful for controlling multiple Minecraft servers with a single definition. It did indeed work fine in my user service.

Cheers.
