### ISSUE TITLE
UI w/base functions POC

### ISSUE THREAD

**Issue by docent-net** [docent-net/mc-server-manager#4]
POC for frontend / UI. Vue.js - powered. Basically a single-page app that lists all servers, marks which one is active and provides following actions:

- add new server
- activate chosen server
- delete server

**Comment by gilesknap** [comment]
Once you have the ui working I would like to do some testing for you. My project is working well enough but I have come to the conclusion that I have no need for multiple servers (as long as one can configure server.properties for each instance - which I understand you do support). I would like to give control of what is running on the server to my son and I think a web gui is better for that.

One thing I do use with my project is ability to attach to the server console. I use the dreaded 'screen' for that. Do you have a solution in mind for this function?

Let me know when you are happy to have another tester.

Thanks.

**Comment by docent-net** [comment]
I'd love to! I still need to work on some more documentation, so the installation of all components is rather trivial.

UI & API servers will need some HTTP server (probably Nginx). Maybe for the 1.0 version, I will provide manual installation commands - that should be fine for the beginning.

Btw - fair you use R-PI. I have some old version somewhere in the basement. Could actually revive it and try installing and test software there (some automated tests running there). This might be actually a good idea as Github actions (I use those for CI) don't provide R-PI environment for running any kind of tests.

Could you tell me what kind of OS you have there? 4 years ago I used Raspbian or something similar, but not sure what ppl use these times :)

**Comment by gilesknap** [comment]
For my 2 raspberry pi4's I'm using Gentoo because it is the only true 64bit
OS at the moment.I did some experiments and convinced myself that Minecraft
performed better on 64bit java.

There is also a 64bit raspbian with a 64 host. That performed well too.

Also I just bought an Intel i7 NUC and that is now the main server,
running Ubuntu.

**Comment by gilesknap** [comment]
FYI, I had a go at getting this working today.

- The CLI got up and running pretty easily.
- The server passes its tests.
- I guess you don't have UI tests yet.
- The UI is up and running and can create new instances, but when I click activate or delete nothing happens and I see no output from the server.
- I've not spent anytime looking into diagnosing yet.

Once I have the UI working, I'll deploy to Noah's Ubuntu server and write up an end-user installation document.

**Comment by docent-net** [comment]
Ui is not working probably because it has hard-coded localhost as backend
address. While it should be the server address as it's requesting from
client (desktop) perspective. I didn't find a way to provide a production
config for the vue.js Ui yet.

**Comment by gilesknap** [comment]
I'm running on local host and it does talk to the server for the create
function.

I'll do some more investigation on the weekend and get back to you.

**Comment by docent-net** [comment]
Sorry - my misunderstanding.

Activate / delete functions are still not implemented :) Only create and
restart for now.

**Comment by docent-net** [comment]
@gilesknap now in v0.4.0 you can activate and restart servers. So there's the only deletion left to implement and all base functionalities will be here :)

**Comment by gilesknap** [comment]
Great, I'll check it out this weekend.

**Comment by gilesknap** [comment]
Restart is now working for me from the GUI, so getting it all set up has been a relatively smooth process.

I have a few questions

- before I deploy to Noah's server I would like to be able to protect against deletion (so the current version is OK!). I think you have plans for this?
- do you think it is OK to simply stop the Minecraft server when switching? The systemd template I used sent a stop command and waited for it to terminate (this was via screen but in future for your project it could be done with RCON)
- I'm a spigot noob but I used it for this deployment since you did. Although I downloaded the 1.15.2 jar it was reporting that it was outdated and pausing for 20 secs at start up. This was a little confusing since there is no way to see the server's output when starting via mc-server-manager. I was only able to fix this by getting their BuildTools.jar and building a new spigot.jar. Is this expected behaviour or am I doing something wrong?

Thanks, giles.

**Comment by docent-net** [comment]
Giles,

1. Yes, securing against deletion is work-in-progress; will be done by tomorrow probably :)
1. Not sure if correctly understood - could you elaborate? :)
1. I'm having the very same issue. I need to rebuild the BuildTools occasionally. However, I'm thinking... maybe you just could use different version (Forge? Vanilla?)

**Comment by gilesknap** [comment]
2. In server_manager.stop_server you call service.Unit.Stop(b"replace"). The question is, will that shut down the minecraft server cleanly, or is there a risk of it corrupting a file it is currently writing to? Normally, I close minecraft by typing stop into the console and it then takes a few seconds to write out data before exiting. (it is quite possible it does the same thing on receiving a signal from systemd - but the spigot monitor UI certainly does not report this happening, it just disappears)

3. Yes I could and probably would switch to vanilla. I see that you have opened a ticket to provide a means to choose your flavour on creation. I'm of the opinion that vanilla requires the least effort for non-experts to come and join your server, but I have not looked into other options in detail.

**Comment by docent-net** [comment]
service.Unit.Sto() does basically the same thing as systemctl stop (sending
a signal to the process) so I wouldn't worry. However you could test it and
compare logs output of both methods
